### ISSUE TITLE
Promo 2018: Materiel

### ISSUE THREAD

**Issue by b300098957** [CollegeBoreal/20H#1]
- [ ] Abbdelkader - Camera

- [ ] Cheick - Internet

- [ ] Echnaideur - PC 

- [ ] Toch - PC

**Comment by toch90** [comment]
> * [ ]  Abbdelkader - Camera
> * [ ]  Cheick - Internet
> * [ ]  Echnaideur - PC
> * [x]  Toch - PC

**Comment by b300098957** [comment]
Merci @toch90
